name: Bug report
description: Report incorrect behaviour
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect, and what happened instead?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Minimal reproducing example
      render: python
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: crosspeak version
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Python version and OS
    validations:
      required: true
